.TH "Set< KeyType, Hash, Equals >::Iterator" 3 "Fri Oct 15 2021" "Symbol Table" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Set< KeyType, Hash, Equals >::Iterator \- Const iterator for a \fBSet\fP\&. May become invalid/give errors after inserting data into the set; to check if an insertion would render the iterators invalid, use \fBwillInvalidateIteratorsOnInsert()\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Set\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::input_iterator_tag \fBiterator_category\fP"
.br
.ti -1c
.RI "typedef KeyType \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef std::ptrdiff_t \fBdifference_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIterator\fP (const KeyType *elem, const State *state, const KeyType *\fBend\fP)"
.br
.ti -1c
.RI "\fBIterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBIterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBIterator\fP other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBIterator\fP other) const"
.br
.ti -1c
.RI "const \fBreference\fP \fBoperator*\fP () const"
.br
.ti -1c
.RI "const \fBpointer\fP \fBoperator\->\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const typedef KeyType * \fBpointer\fP"
.br
.ti -1c
.RI "const typedef KeyType & \fBreference\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSet\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class KeyType, class Hash = std::hash<KeyType>, class Equals = std::equal_to<KeyType>>
.br
class Set< KeyType, Hash, Equals >::Iterator"
Const iterator for a \fBSet\fP\&. May become invalid/give errors after inserting data into the set; to check if an insertion would render the iterators invalid, use \fBwillInvalidateIteratorsOnInsert()\fP 


.PP
Definition at line 63 of file Set\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class KeyType, class Hash = std::hash<KeyType>, class Equals = std::equal_to<KeyType>> typedef std::ptrdiff_t \fBSet\fP< KeyType, Hash, Equals >::\fBIterator::difference_type\fP"

.PP
Definition at line 70 of file Set\&.hpp\&.
.SS "template<class KeyType, class Hash = std::hash<KeyType>, class Equals = std::equal_to<KeyType>> typedef std::input_iterator_tag \fBSet\fP< KeyType, Hash, Equals >::\fBIterator::iterator_category\fP"

.PP
Definition at line 68 of file Set\&.hpp\&.
.SS "template<class KeyType, class Hash = std::hash<KeyType>, class Equals = std::equal_to<KeyType>> typedef KeyType \fBSet\fP< KeyType, Hash, Equals >::\fBIterator::value_type\fP"

.PP
Definition at line 69 of file Set\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class KeyType, class Hash = std::hash<KeyType>, class Equals = std::equal_to<KeyType>> \fBSet\fP< KeyType, Hash, Equals >::Iterator::Iterator (const KeyType * elem, const State * state, const KeyType * end)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 74 of file Set\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class KeyType , class Hash , class Equals > bool \fBSet\fP< KeyType, Hash, Equals >::Iterator::operator!= (\fBIterator\fP other) const\fC [inline]\fP"

.PP
Definition at line 334 of file Set\&.hpp\&.
.SS "template<class KeyType , class Hash , class Equals > const \fBSet\fP< KeyType, Hash, Equals >::\fBIterator::reference\fP \fBSet\fP< KeyType, Hash, Equals >::Iterator::operator* () const\fC [inline]\fP"

.PP
Definition at line 340 of file Set\&.hpp\&.
.SS "template<class KeyType , class Hash , class Equals > \fBSet\fP< KeyType, Hash, Equals >::\fBIterator\fP & \fBSet\fP< KeyType, Hash, Equals >::Iterator::operator++ ()\fC [inline]\fP"

.PP
Definition at line 306 of file Set\&.hpp\&.
.SS "template<class KeyType , class Hash , class Equals > \fBSet\fP< KeyType, Hash, Equals >::\fBIterator\fP \fBSet\fP< KeyType, Hash, Equals >::Iterator::operator++ (int)\fC [inline]\fP"

.PP
Definition at line 320 of file Set\&.hpp\&.
.SS "template<class KeyType , class Hash , class Equals > const \fBSet\fP< KeyType, Hash, Equals >::\fBIterator::pointer\fP \fBSet\fP< KeyType, Hash, Equals >::Iterator::operator\-> () const\fC [inline]\fP"

.PP
Definition at line 346 of file Set\&.hpp\&.
.SS "template<class KeyType , class Hash , class Equals > bool \fBSet\fP< KeyType, Hash, Equals >::Iterator::operator== (\fBIterator\fP other) const\fC [inline]\fP"

.PP
Definition at line 328 of file Set\&.hpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class KeyType, class Hash = std::hash<KeyType>, class Equals = std::equal_to<KeyType>> friend class \fBSet\fP\fC [friend]\fP"

.PP
Definition at line 66 of file Set\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class KeyType, class Hash = std::hash<KeyType>, class Equals = std::equal_to<KeyType>> const typedef KeyType* \fBSet\fP< KeyType, Hash, Equals >::Iterator::pointer"

.PP
Definition at line 71 of file Set\&.hpp\&.
.SS "template<class KeyType, class Hash = std::hash<KeyType>, class Equals = std::equal_to<KeyType>> const typedef KeyType& \fBSet\fP< KeyType, Hash, Equals >::Iterator::reference"

.PP
Definition at line 72 of file Set\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Symbol Table from the source code\&.
