.TH "SymbolTable" 3 "Fri Oct 15 2021" "Symbol Table" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SymbolTable \- Symbol table data structure\&. Features iterators that will sometimes get updated on insert, so that they are never invalid  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SymbolTable\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPosition\fP"
.br
.RI "Symbol table const iterator\&. Will still be valid after inserts in the parent \fBSymbolTable\fP "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::pair< \fBPosition\fP, bool > \fBinsert\fP (const std::string &symbol)"
.br
.RI "Inserts a symbol into the symbol table "
.ti -1c
.RI "\fBPosition\fP \fBfind\fP (const std::string &symbol)"
.br
.RI "Searches for an entry in the \fBSymbolTable\fP "
.ti -1c
.RI "\fBPosition\fP \fBbegin\fP ()"
.br
.ti -1c
.RI "\fBPosition\fP \fBend\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Symbol table data structure\&. Features iterators that will sometimes get updated on insert, so that they are never invalid 


.PP
Definition at line 9 of file SymbolTable\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSymbolTable::Position\fP SymbolTable::begin ()"

.PP
Definition at line 43 of file SymbolTable\&.cpp\&.
.SS "\fBSymbolTable::Position\fP SymbolTable::end ()"

.PP
Definition at line 48 of file SymbolTable\&.cpp\&.
.SS "\fBSymbolTable::Position\fP SymbolTable::find (const std::string & symbol)"

.PP
Searches for an entry in the \fBSymbolTable\fP 
.PP
\fBParameters\fP
.RS 4
\fIsymbol\fP The symbol to look for
.RE
.PP
\fBReturns\fP
.RS 4
\fBPosition\fP to the symbol or \fBend()\fP if it was not found
.RE
.PP

.PP
Definition at line 38 of file SymbolTable\&.cpp\&.
.SS "std::pair< typename \fBSymbolTable::Position\fP, bool > SymbolTable::insert (const std::string & symbol)"

.PP
Inserts a symbol into the symbol table 
.PP
\fBParameters\fP
.RS 4
\fIsymbol\fP The symbol to insert
.RE
.PP
\fBReturns\fP
.RS 4
A \fBPosition\fP of where the symbol is and whether or not the insertion happened; if a similar symbol already exists in the table, the \fBPosition\fP points to that 
.RE
.PP

.PP
Definition at line 6 of file SymbolTable\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Symbol Table from the source code\&.
