.TH "SymbolTable.h" 3 "Fri Oct 15 2021" "Symbol Table" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SymbolTable.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Set\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSymbolTable\fP"
.br
.RI "Symbol table data structure\&. Features iterators that will sometimes get updated on insert, so that they are never invalid "
.ti -1c
.RI "class \fBSymbolTable::Position\fP"
.br
.RI "Symbol table const iterator\&. Will still be valid after inserts in the parent \fBSymbolTable\fP "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Symbol Table from the source code\&.
